<! DOCTYPE html>
    <html>

    <head>
        <meta charset="utf-8">
        <title>Products Export</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                font-size: 12px;
            }

            h1 {
                text-align: center;
                color: #333;
                margin-bottom: 20px;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            th {
                background-color: #4CAF50;
                color: white;
                padding: 10px;
                text-align: left;
                border: 1px solid #ddd;
            }

            td {
                padding: 8px;
                border: 1px solid #ddd;
            }

            tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            .footer {
                margin-top: 30px;
                text-align: center;
                font-size: 10px;
                color: #666;
            }

            .badge {
                padding: 3px 8px;
                border-radius: 3px;
                font-size: 10px;
            }

            . badge-success {
                background-color: #4CAF50;
                color: white;
            }

            .badge-danger {
                background-color: #f44336;
                color: white;
            }

            .badge-warning {
                background-color: #ff9800;
                color: white;
            }
        </style>
    </head>

    <body>
        <h1>Products Export</h1>
        <p><strong>Generated:</strong> {{ now()->format('d M Y H:i:s') }}</p>
        <p><strong>Total Products:</strong> {{ $products->count() }}</p>

        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>SKU</th>
                    <th>Product Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Stock</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $index => $product)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $product->sku }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->category->name ?? '-' }}</td>
                        <td>Rp {{ number_format($product->price, 0, ',', '.') }}</td>
                        <td>
                            @if ($product->stock == 0)
                                <span class="badge badge-danger">{{ $product->stock }}</span>
                            @elseif($product->stock < 10)
                                <span class="badge badge-warning">{{ $product->stock }}</span>
                            @else
                                <span class="badge badge-success">{{ $product->stock }}</span>
                            @endif
                        </td>
                        <td>
                            @if ($product->is_active)
                                <span class="badge badge-success">Active</span>
                            @else
                                <span class="badge badge-danger">Inactive</span>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by {{ config('app.name') }} | {{ now()->format('Y') }}</p>
        </div>
    </body>

    </html>
