<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Transactions Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background-color: #2196F3;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }

        td {
            padding: 8px;
            border: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }

        .badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
        }

        .badge-success {
            background-color: #4CAF50;
            color: white;
        }

        .badge-warning {
            background-color: #ff9800;
            color: white;
        }

        .badge-info {
            background-color: #2196F3;
            color: white;
        }

        .badge-danger {
            background-color: #f44336;
            color: white;
        }
    </style>
</head>

<body>
    <h1>Transactions Export</h1>
    <p><strong>Generated:</strong> {{ now()->format('d M Y H:i:s') }}</p>
    <p><strong>Total Transactions:</strong> {{ $transactions->count() }}</p>
    <p><strong>Total Revenue:</strong> Rp {{ number_format($transactions->sum('total_amount'), 0, ',', '.') }}</p>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Order Number</th>
                <th>Customer</th>
                <th>Total</th>
                <th>Status</th>
                <th>Payment</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($transactions as $index => $transaction)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $transaction->order_number }}</td>
                    <td>{{ $transaction->user->name ?? '-' }}</td>
                    <td>Rp {{ number_format($transaction->total_amount, 0, ',', '.') }}</td>
                    <td>
                        @php
                            $statusClass = match ($transaction->status) {
                                'completed' => 'badge-success',
                                'pending' => 'badge-warning',
                                'processing', 'paid' => 'badge-info',
                                'cancelled' => 'badge-danger',
                                default => 'badge-info',
                            };
                        @endphp
                        <span class="badge {{ $statusClass }}">{{ ucfirst($transaction->status) }}</span>
                    </td>
                    <td>{{ ucfirst($transaction->payment_method ?? '-') }}</td>
                    <td>{{ $transaction->created_at->format('d M Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} | {{ now()->format('Y') }}</p>
    </div>
</body>

</html>
